"""Plugin protocol for ProTest."""

from typing import Protocol, runtime_checkable

from protest.core.session import ProTestSession
from protest.events.data import SessionResult, TestResult


@runtime_checkable
class Plugin(Protocol):
    """Contrat pour les plugins ProTest."""

    def setup(self, session: ProTestSession) -> None: ...
    def on_session_start(self) -> None: ...
    def on_session_end(self, result: SessionResult) -> None: ...
    def on_session_complete(self, result: SessionResult) -> None: ...
    def on_suite_start(self, name: str) -> None: ...
    def on_suite_end(self, name: str) -> None: ...
    def on_test_pass(self, result: TestResult) -> None: ...
    def on_test_fail(self, result: TestResult) -> None: ...
