"""Reporter protocol for test execution events."""

from typing import Protocol


class Reporter(Protocol):
    """Protocol for reporting test execution events."""

    def on_session_start(self) -> None: ...
    def on_session_end(self, passed: int, failed: int) -> None: ...
    def on_suite_start(self, suite_name: str) -> None: ...
    def on_suite_end(self, suite_name: str) -> None: ...
    def on_test_pass(self, test_name: str) -> None: ...
    def on_test_fail(self, test_name: str, error: Exception) -> None: ...
